//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbUserServiceServiceSoapBinding", Namespace="http://user.impl.business.sdi.com/")]
public partial class EjbUserServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback findByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback saveUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUsersOperationCompleted;
    
    private System.Threading.SendOrPostCallback unsubscribeOperationCompleted;
    
    private System.Threading.SendOrPostCallback finByLoginOperationCompleted;
    
    /// <remarks/>
    public EjbUserServiceService() {
        this.Url = "http://DESKTOP-MFFUMQQ:8280/sdi3-13.EJB/UserService";
    }
    
    /// <remarks/>
    public event findByIdCompletedEventHandler findByIdCompleted;
    
    /// <remarks/>
    public event saveUserCompletedEventHandler saveUserCompleted;
    
    /// <remarks/>
    public event getUsersCompletedEventHandler getUsersCompleted;
    
    /// <remarks/>
    public event unsubscribeCompletedEventHandler unsubscribeCompleted;
    
    /// <remarks/>
    public event finByLoginCompletedEventHandler finByLoginCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://user.impl.business.sdi.com/", ResponseNamespace="http://user.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user findById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findById", new object[] {
                    arg0,
                    arg0Specified});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindById(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findById", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndfindById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void findByIdAsync(long arg0, bool arg0Specified) {
        this.findByIdAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByIdAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByIdOperationCompleted == null)) {
            this.findByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByIdOperationCompleted);
        }
        this.InvokeAsync("findById", new object[] {
                    arg0,
                    arg0Specified}, this.findByIdOperationCompleted, userState);
    }
    
    private void OnfindByIdOperationCompleted(object arg) {
        if ((this.findByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByIdCompleted(this, new findByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://user.impl.business.sdi.com/", ResponseNamespace="http://user.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void saveUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        this.Invoke("saveUser", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsaveUser(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("saveUser", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsaveUser(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void saveUserAsync(user arg0) {
        this.saveUserAsync(arg0, null);
    }
    
    /// <remarks/>
    public void saveUserAsync(user arg0, object userState) {
        if ((this.saveUserOperationCompleted == null)) {
            this.saveUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveUserOperationCompleted);
        }
        this.InvokeAsync("saveUser", new object[] {
                    arg0}, this.saveUserOperationCompleted, userState);
    }
    
    private void OnsaveUserOperationCompleted(object arg) {
        if ((this.saveUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://user.impl.business.sdi.com/", ResponseNamespace="http://user.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user[] getUsers() {
        object[] results = this.Invoke("getUsers", new object[0]);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUsers(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUsers", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public user[] EndgetUsers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public void getUsersAsync() {
        this.getUsersAsync(null);
    }
    
    /// <remarks/>
    public void getUsersAsync(object userState) {
        if ((this.getUsersOperationCompleted == null)) {
            this.getUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsersOperationCompleted);
        }
        this.InvokeAsync("getUsers", new object[0], this.getUsersOperationCompleted, userState);
    }
    
    private void OngetUsersOperationCompleted(object arg) {
        if ((this.getUsersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUsersCompleted(this, new getUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://user.impl.business.sdi.com/", ResponseNamespace="http://user.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void unsubscribe([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        this.Invoke("unsubscribe", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginunsubscribe(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("unsubscribe", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endunsubscribe(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void unsubscribeAsync(string arg0) {
        this.unsubscribeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void unsubscribeAsync(string arg0, object userState) {
        if ((this.unsubscribeOperationCompleted == null)) {
            this.unsubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsubscribeOperationCompleted);
        }
        this.InvokeAsync("unsubscribe", new object[] {
                    arg0}, this.unsubscribeOperationCompleted, userState);
    }
    
    private void OnunsubscribeOperationCompleted(object arg) {
        if ((this.unsubscribeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.unsubscribeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://user.impl.business.sdi.com/", ResponseNamespace="http://user.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user finByLogin([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("finByLogin", new object[] {
                    arg0});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfinByLogin(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("finByLogin", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndfinByLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void finByLoginAsync(string arg0) {
        this.finByLoginAsync(arg0, null);
    }
    
    /// <remarks/>
    public void finByLoginAsync(string arg0, object userState) {
        if ((this.finByLoginOperationCompleted == null)) {
            this.finByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinByLoginOperationCompleted);
        }
        this.InvokeAsync("finByLogin", new object[] {
                    arg0}, this.finByLoginOperationCompleted, userState);
    }
    
    private void OnfinByLoginOperationCompleted(object arg) {
        if ((this.finByLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.finByLoginCompleted(this, new finByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.impl.business.sdi.com/")]
public partial class user {
    
    private string emailField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string loginField;
    
    private string nameField;
    
    private string passwordField;
    
    private userStatus statusField;
    
    private bool statusFieldSpecified;
    
    private string surnameField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.impl.business.sdi.com/")]
public enum userStatus {
    
    /// <comentarios/>
    ACTIVE,
    
    /// <comentarios/>
    CANCELLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByIdCompletedEventHandler(object sender, findByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void saveUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getUsersCompletedEventHandler(object sender, getUsersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void unsubscribeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void finByLoginCompletedEventHandler(object sender, finByLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class finByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal finByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}
