//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbApplicationServiceServiceSoapBinding", Namespace="http://application.impl.business.sdi.com/")]
public partial class EjbApplicationServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback deleteOperationCompleted;
    
    private System.Threading.SendOrPostCallback getSolicitudesViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getSolicitudesOperationCompleted;
    
    private System.Threading.SendOrPostCallback saveOperationCompleted;
    
    /// <remarks/>
    public EjbApplicationServiceService() {
        this.Url = "http://localhost:8280/sdi3-13.EJB/ApplicationService";
    }
    
    /// <remarks/>
    public event deleteCompletedEventHandler deleteCompleted;
    
    /// <remarks/>
    public event getSolicitudesViajeCompletedEventHandler getSolicitudesViajeCompleted;
    
    /// <remarks/>
    public event getSolicitudesCompletedEventHandler getSolicitudesCompleted;
    
    /// <remarks/>
    public event saveCompletedEventHandler saveCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://application.impl.business.sdi.com/", ResponseNamespace="http://application.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified) {
        this.Invoke("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begindelete(long arg0, bool arg0Specified, long arg1, bool arg1Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Enddelete(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified) {
        this.deleteAsync(arg0, arg0Specified, arg1, arg1Specified, null);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, long arg1, bool arg1Specified, object userState) {
        if ((this.deleteOperationCompleted == null)) {
            this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
        }
        this.InvokeAsync("delete", new object[] {
                    arg0,
                    arg0Specified,
                    arg1,
                    arg1Specified}, this.deleteOperationCompleted, userState);
    }
    
    private void OndeleteOperationCompleted(object arg) {
        if ((this.deleteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://application.impl.business.sdi.com/", ResponseNamespace="http://application.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public application[] getSolicitudesViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("getSolicitudesViaje", new object[] {
                    arg0,
                    arg0Specified});
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetSolicitudesViaje(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getSolicitudesViaje", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public application[] EndgetSolicitudesViaje(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public void getSolicitudesViajeAsync(long arg0, bool arg0Specified) {
        this.getSolicitudesViajeAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void getSolicitudesViajeAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.getSolicitudesViajeOperationCompleted == null)) {
            this.getSolicitudesViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSolicitudesViajeOperationCompleted);
        }
        this.InvokeAsync("getSolicitudesViaje", new object[] {
                    arg0,
                    arg0Specified}, this.getSolicitudesViajeOperationCompleted, userState);
    }
    
    private void OngetSolicitudesViajeOperationCompleted(object arg) {
        if ((this.getSolicitudesViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getSolicitudesViajeCompleted(this, new getSolicitudesViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://application.impl.business.sdi.com/", ResponseNamespace="http://application.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public application[] getSolicitudes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("getSolicitudes", new object[] {
                    arg0});
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetSolicitudes(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getSolicitudes", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public application[] EndgetSolicitudes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public void getSolicitudesAsync(string arg0) {
        this.getSolicitudesAsync(arg0, null);
    }
    
    /// <remarks/>
    public void getSolicitudesAsync(string arg0, object userState) {
        if ((this.getSolicitudesOperationCompleted == null)) {
            this.getSolicitudesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSolicitudesOperationCompleted);
        }
        this.InvokeAsync("getSolicitudes", new object[] {
                    arg0}, this.getSolicitudesOperationCompleted, userState);
    }
    
    private void OngetSolicitudesOperationCompleted(object arg) {
        if ((this.getSolicitudesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getSolicitudesCompleted(this, new getSolicitudesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://application.impl.business.sdi.com/", ResponseNamespace="http://application.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void save([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified) {
        this.Invoke("save", new object[] {
                    arg0,
                    arg1,
                    arg1Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsave(string arg0, long arg1, bool arg1Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("save", new object[] {
                    arg0,
                    arg1,
                    arg1Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endsave(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void saveAsync(string arg0, long arg1, bool arg1Specified) {
        this.saveAsync(arg0, arg1, arg1Specified, null);
    }
    
    /// <remarks/>
    public void saveAsync(string arg0, long arg1, bool arg1Specified, object userState) {
        if ((this.saveOperationCompleted == null)) {
            this.saveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveOperationCompleted);
        }
        this.InvokeAsync("save", new object[] {
                    arg0,
                    arg1,
                    arg1Specified}, this.saveOperationCompleted, userState);
    }
    
    private void OnsaveOperationCompleted(object arg) {
        if ((this.saveCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://application.impl.business.sdi.com/")]
public partial class application {
    
    private long tripIdField;
    
    private bool tripIdFieldSpecified;
    
    private long userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long tripId {
        get {
            return this.tripIdField;
        }
        set {
            this.tripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tripIdSpecified {
        get {
            return this.tripIdFieldSpecified;
        }
        set {
            this.tripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void deleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getSolicitudesViajeCompletedEventHandler(object sender, getSolicitudesViajeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getSolicitudesViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getSolicitudesViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public application[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((application[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getSolicitudesCompletedEventHandler(object sender, getSolicitudesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getSolicitudesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getSolicitudesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public application[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((application[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void saveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
