//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbRatingServiceServiceSoapBinding", Namespace="http://rating.impl.business.sdi.com/")]
public partial class EjbRatingServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback findByAboutUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback deleteOperationCompleted;
    
    private System.Threading.SendOrPostCallback findLastMonthOperationCompleted;
    
    /// <remarks/>
    public EjbRatingServiceService() {
        this.Url = "http://DESKTOP-MFFUMQQ:8280/sdi3-13.EJB/RatingService";
    }
    
    /// <remarks/>
    public event findByAboutUserCompletedEventHandler findByAboutUserCompleted;
    
    /// <remarks/>
    public event deleteCompletedEventHandler deleteCompleted;
    
    /// <remarks/>
    public event findLastMonthCompletedEventHandler findLastMonthCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rating.impl.business.sdi.com/", ResponseNamespace="http://rating.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] findByAboutUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByAboutUser", new object[] {
                    arg0,
                    arg0Specified});
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByAboutUser(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByAboutUser", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndfindByAboutUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void findByAboutUserAsync(long arg0, bool arg0Specified) {
        this.findByAboutUserAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByAboutUserAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByAboutUserOperationCompleted == null)) {
            this.findByAboutUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByAboutUserOperationCompleted);
        }
        this.InvokeAsync("findByAboutUser", new object[] {
                    arg0,
                    arg0Specified}, this.findByAboutUserOperationCompleted, userState);
    }
    
    private void OnfindByAboutUserOperationCompleted(object arg) {
        if ((this.findByAboutUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByAboutUserCompleted(this, new findByAboutUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rating.impl.business.sdi.com/", ResponseNamespace="http://rating.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("delete", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begindelete(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("delete", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Enddelete(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified) {
        this.deleteAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void deleteAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.deleteOperationCompleted == null)) {
            this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
        }
        this.InvokeAsync("delete", new object[] {
                    arg0,
                    arg0Specified}, this.deleteOperationCompleted, userState);
    }
    
    private void OndeleteOperationCompleted(object arg) {
        if ((this.deleteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://rating.impl.business.sdi.com/", ResponseNamespace="http://rating.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] findLastMonth() {
        object[] results = this.Invoke("findLastMonth", new object[0]);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindLastMonth(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findLastMonth", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndfindLastMonth(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void findLastMonthAsync() {
        this.findLastMonthAsync(null);
    }
    
    /// <remarks/>
    public void findLastMonthAsync(object userState) {
        if ((this.findLastMonthOperationCompleted == null)) {
            this.findLastMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindLastMonthOperationCompleted);
        }
        this.InvokeAsync("findLastMonth", new object[0], this.findLastMonthOperationCompleted, userState);
    }
    
    private void OnfindLastMonthOperationCompleted(object arg) {
        if ((this.findLastMonthCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findLastMonthCompleted(this, new findLastMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rating.impl.business.sdi.com/")]
public partial class rating {
    
    private string commentField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private long seatAboutTripIdField;
    
    private bool seatAboutTripIdFieldSpecified;
    
    private long seatAboutUserIdField;
    
    private bool seatAboutUserIdFieldSpecified;
    
    private long seatFromTripIdField;
    
    private bool seatFromTripIdFieldSpecified;
    
    private long seatFromUserIdField;
    
    private bool seatFromUserIdFieldSpecified;
    
    private int valueField;
    
    private bool valueFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutTripId {
        get {
            return this.seatAboutTripIdField;
        }
        set {
            this.seatAboutTripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutTripIdSpecified {
        get {
            return this.seatAboutTripIdFieldSpecified;
        }
        set {
            this.seatAboutTripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutUserId {
        get {
            return this.seatAboutUserIdField;
        }
        set {
            this.seatAboutUserIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutUserIdSpecified {
        get {
            return this.seatAboutUserIdFieldSpecified;
        }
        set {
            this.seatAboutUserIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromTripId {
        get {
            return this.seatFromTripIdField;
        }
        set {
            this.seatFromTripIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromTripIdSpecified {
        get {
            return this.seatFromTripIdFieldSpecified;
        }
        set {
            this.seatFromTripIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromUserId {
        get {
            return this.seatFromUserIdField;
        }
        set {
            this.seatFromUserIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromUserIdSpecified {
        get {
            return this.seatFromUserIdFieldSpecified;
        }
        set {
            this.seatFromUserIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByAboutUserCompletedEventHandler(object sender, findByAboutUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByAboutUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByAboutUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findLastMonthCompletedEventHandler(object sender, findLastMonthCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findLastMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findLastMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}
