//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbTripServiceServiceSoapBinding", Namespace="http://trip.impl.business.sdi.com/")]
public partial class EjbTripServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback registrarOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByIdTripOperationCompleted;
    
    private System.Threading.SendOrPostCallback findViajesHaParticipadoOperationCompleted;
    
    private System.Threading.SendOrPostCallback cancelarViajesOperationCompleted;
    
    private System.Threading.SendOrPostCallback liberarPlazaOperationCompleted;
    
    private System.Threading.SendOrPostCallback actualizarOperationCompleted;
    
    private System.Threading.SendOrPostCallback modificarOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByPromoterAndAvailablePaxOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByPromoterAndDoneOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByAceptadoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ocuparPlazaOperationCompleted;
    
    private System.Threading.SendOrPostCallback cerrarViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback viajesFechaCierrePasadaOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByPromoterOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllDisponibleOperationCompleted;
    
    private System.Threading.SendOrPostCallback findLastMonthTripOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllDisponibleUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback findAllTripOperationCompleted;
    
    /// <remarks/>
    public EjbTripServiceService() {
        this.Url = "http://localhost:8280/sdi3-13.EJB/TripService";
    }
    
    /// <remarks/>
    public event registrarCompletedEventHandler registrarCompleted;
    
    /// <remarks/>
    public event findByIdTripCompletedEventHandler findByIdTripCompleted;
    
    /// <remarks/>
    public event findViajesHaParticipadoCompletedEventHandler findViajesHaParticipadoCompleted;
    
    /// <remarks/>
    public event cancelarViajesCompletedEventHandler cancelarViajesCompleted;
    
    /// <remarks/>
    public event liberarPlazaCompletedEventHandler liberarPlazaCompleted;
    
    /// <remarks/>
    public event actualizarCompletedEventHandler actualizarCompleted;
    
    /// <remarks/>
    public event modificarCompletedEventHandler modificarCompleted;
    
    /// <remarks/>
    public event findByPromoterAndAvailablePaxCompletedEventHandler findByPromoterAndAvailablePaxCompleted;
    
    /// <remarks/>
    public event findByPromoterAndDoneCompletedEventHandler findByPromoterAndDoneCompleted;
    
    /// <remarks/>
    public event findByAceptadoCompletedEventHandler findByAceptadoCompleted;
    
    /// <remarks/>
    public event ocuparPlazaCompletedEventHandler ocuparPlazaCompleted;
    
    /// <remarks/>
    public event cerrarViajeCompletedEventHandler cerrarViajeCompleted;
    
    /// <remarks/>
    public event viajesFechaCierrePasadaCompletedEventHandler viajesFechaCierrePasadaCompleted;
    
    /// <remarks/>
    public event findByPromoterCompletedEventHandler findByPromoterCompleted;
    
    /// <remarks/>
    public event findAllDisponibleCompletedEventHandler findAllDisponibleCompleted;
    
    /// <remarks/>
    public event findLastMonthTripCompletedEventHandler findLastMonthTripCompleted;
    
    /// <remarks/>
    public event findAllDisponibleUserCompletedEventHandler findAllDisponibleUserCompleted;
    
    /// <remarks/>
    public event findAllTripCompletedEventHandler findAllTripCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool registrar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] registrarViajeDto arg0) {
        object[] results = this.Invoke("registrar", new object[] {
                    arg0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginregistrar(registrarViajeDto arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("registrar", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endregistrar(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void registrarAsync(registrarViajeDto arg0) {
        this.registrarAsync(arg0, null);
    }
    
    /// <remarks/>
    public void registrarAsync(registrarViajeDto arg0, object userState) {
        if ((this.registrarOperationCompleted == null)) {
            this.registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarOperationCompleted);
        }
        this.InvokeAsync("registrar", new object[] {
                    arg0}, this.registrarOperationCompleted, userState);
    }
    
    private void OnregistrarOperationCompleted(object arg) {
        if ((this.registrarCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.registrarCompleted(this, new registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip findByIdTrip([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByIdTrip", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByIdTrip(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByIdTrip", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip EndfindByIdTrip(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public void findByIdTripAsync(long arg0, bool arg0Specified) {
        this.findByIdTripAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByIdTripAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByIdTripOperationCompleted == null)) {
            this.findByIdTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByIdTripOperationCompleted);
        }
        this.InvokeAsync("findByIdTrip", new object[] {
                    arg0,
                    arg0Specified}, this.findByIdTripOperationCompleted, userState);
    }
    
    private void OnfindByIdTripOperationCompleted(object arg) {
        if ((this.findByIdTripCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByIdTripCompleted(this, new findByIdTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findViajesHaParticipado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findViajesHaParticipado", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindViajesHaParticipado(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findViajesHaParticipado", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindViajesHaParticipado(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findViajesHaParticipadoAsync(long arg0, bool arg0Specified) {
        this.findViajesHaParticipadoAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findViajesHaParticipadoAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findViajesHaParticipadoOperationCompleted == null)) {
            this.findViajesHaParticipadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindViajesHaParticipadoOperationCompleted);
        }
        this.InvokeAsync("findViajesHaParticipado", new object[] {
                    arg0,
                    arg0Specified}, this.findViajesHaParticipadoOperationCompleted, userState);
    }
    
    private void OnfindViajesHaParticipadoOperationCompleted(object arg) {
        if ((this.findViajesHaParticipadoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findViajesHaParticipadoCompleted(this, new findViajesHaParticipadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void cancelarViajes([System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] cancelarViajesEntry[] arg0) {
        this.Invoke("cancelarViajes", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincancelarViajes(cancelarViajesEntry[] arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("cancelarViajes", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcancelarViajes(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void cancelarViajesAsync(cancelarViajesEntry[] arg0) {
        this.cancelarViajesAsync(arg0, null);
    }
    
    /// <remarks/>
    public void cancelarViajesAsync(cancelarViajesEntry[] arg0, object userState) {
        if ((this.cancelarViajesOperationCompleted == null)) {
            this.cancelarViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarViajesOperationCompleted);
        }
        this.InvokeAsync("cancelarViajes", new object[] {
                    arg0}, this.cancelarViajesOperationCompleted, userState);
    }
    
    private void OncancelarViajesOperationCompleted(object arg) {
        if ((this.cancelarViajesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.cancelarViajesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void liberarPlaza([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("liberarPlaza", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginliberarPlaza(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("liberarPlaza", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndliberarPlaza(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void liberarPlazaAsync(long arg0, bool arg0Specified) {
        this.liberarPlazaAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void liberarPlazaAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.liberarPlazaOperationCompleted == null)) {
            this.liberarPlazaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnliberarPlazaOperationCompleted);
        }
        this.InvokeAsync("liberarPlaza", new object[] {
                    arg0,
                    arg0Specified}, this.liberarPlazaOperationCompleted, userState);
    }
    
    private void OnliberarPlazaOperationCompleted(object arg) {
        if ((this.liberarPlazaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.liberarPlazaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void actualizar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        this.Invoke("actualizar", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginactualizar(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("actualizar", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endactualizar(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void actualizarAsync(trip arg0) {
        this.actualizarAsync(arg0, null);
    }
    
    /// <remarks/>
    public void actualizarAsync(trip arg0, object userState) {
        if ((this.actualizarOperationCompleted == null)) {
            this.actualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarOperationCompleted);
        }
        this.InvokeAsync("actualizar", new object[] {
                    arg0}, this.actualizarOperationCompleted, userState);
    }
    
    private void OnactualizarOperationCompleted(object arg) {
        if ((this.actualizarCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.actualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool modificar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] modificarViajeDto arg0) {
        object[] results = this.Invoke("modificar", new object[] {
                    arg0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmodificar(modificarViajeDto arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("modificar", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endmodificar(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void modificarAsync(modificarViajeDto arg0) {
        this.modificarAsync(arg0, null);
    }
    
    /// <remarks/>
    public void modificarAsync(modificarViajeDto arg0, object userState) {
        if ((this.modificarOperationCompleted == null)) {
            this.modificarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarOperationCompleted);
        }
        this.InvokeAsync("modificar", new object[] {
                    arg0}, this.modificarOperationCompleted, userState);
    }
    
    private void OnmodificarOperationCompleted(object arg) {
        if ((this.modificarCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.modificarCompleted(this, new modificarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findByPromoterAndAvailablePax([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByPromoterAndAvailablePax", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByPromoterAndAvailablePax(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByPromoterAndAvailablePax", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindByPromoterAndAvailablePax(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findByPromoterAndAvailablePaxAsync(long arg0, bool arg0Specified) {
        this.findByPromoterAndAvailablePaxAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByPromoterAndAvailablePaxAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByPromoterAndAvailablePaxOperationCompleted == null)) {
            this.findByPromoterAndAvailablePaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByPromoterAndAvailablePaxOperationCompleted);
        }
        this.InvokeAsync("findByPromoterAndAvailablePax", new object[] {
                    arg0,
                    arg0Specified}, this.findByPromoterAndAvailablePaxOperationCompleted, userState);
    }
    
    private void OnfindByPromoterAndAvailablePaxOperationCompleted(object arg) {
        if ((this.findByPromoterAndAvailablePaxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByPromoterAndAvailablePaxCompleted(this, new findByPromoterAndAvailablePaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findByPromoterAndDone([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByPromoterAndDone", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByPromoterAndDone(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByPromoterAndDone", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindByPromoterAndDone(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findByPromoterAndDoneAsync(long arg0, bool arg0Specified) {
        this.findByPromoterAndDoneAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByPromoterAndDoneAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByPromoterAndDoneOperationCompleted == null)) {
            this.findByPromoterAndDoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByPromoterAndDoneOperationCompleted);
        }
        this.InvokeAsync("findByPromoterAndDone", new object[] {
                    arg0,
                    arg0Specified}, this.findByPromoterAndDoneOperationCompleted, userState);
    }
    
    private void OnfindByPromoterAndDoneOperationCompleted(object arg) {
        if ((this.findByPromoterAndDoneCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByPromoterAndDoneCompleted(this, new findByPromoterAndDoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findByAceptado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByAceptado", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByAceptado(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByAceptado", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindByAceptado(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findByAceptadoAsync(long arg0, bool arg0Specified) {
        this.findByAceptadoAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByAceptadoAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByAceptadoOperationCompleted == null)) {
            this.findByAceptadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByAceptadoOperationCompleted);
        }
        this.InvokeAsync("findByAceptado", new object[] {
                    arg0,
                    arg0Specified}, this.findByAceptadoOperationCompleted, userState);
    }
    
    private void OnfindByAceptadoOperationCompleted(object arg) {
        if ((this.findByAceptadoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByAceptadoCompleted(this, new findByAceptadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ocuparPlaza([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("ocuparPlaza", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginocuparPlaza(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ocuparPlaza", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndocuparPlaza(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void ocuparPlazaAsync(long arg0, bool arg0Specified) {
        this.ocuparPlazaAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void ocuparPlazaAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.ocuparPlazaOperationCompleted == null)) {
            this.ocuparPlazaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnocuparPlazaOperationCompleted);
        }
        this.InvokeAsync("ocuparPlaza", new object[] {
                    arg0,
                    arg0Specified}, this.ocuparPlazaOperationCompleted, userState);
    }
    
    private void OnocuparPlazaOperationCompleted(object arg) {
        if ((this.ocuparPlazaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ocuparPlazaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void cerrarViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        this.Invoke("cerrarViaje", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincerrarViaje(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("cerrarViaje", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcerrarViaje(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void cerrarViajeAsync(trip arg0) {
        this.cerrarViajeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void cerrarViajeAsync(trip arg0, object userState) {
        if ((this.cerrarViajeOperationCompleted == null)) {
            this.cerrarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncerrarViajeOperationCompleted);
        }
        this.InvokeAsync("cerrarViaje", new object[] {
                    arg0}, this.cerrarViajeOperationCompleted, userState);
    }
    
    private void OncerrarViajeOperationCompleted(object arg) {
        if ((this.cerrarViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.cerrarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] viajesFechaCierrePasada() {
        object[] results = this.Invoke("viajesFechaCierrePasada", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginviajesFechaCierrePasada(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("viajesFechaCierrePasada", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndviajesFechaCierrePasada(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void viajesFechaCierrePasadaAsync() {
        this.viajesFechaCierrePasadaAsync(null);
    }
    
    /// <remarks/>
    public void viajesFechaCierrePasadaAsync(object userState) {
        if ((this.viajesFechaCierrePasadaOperationCompleted == null)) {
            this.viajesFechaCierrePasadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviajesFechaCierrePasadaOperationCompleted);
        }
        this.InvokeAsync("viajesFechaCierrePasada", new object[0], this.viajesFechaCierrePasadaOperationCompleted, userState);
    }
    
    private void OnviajesFechaCierrePasadaOperationCompleted(object arg) {
        if ((this.viajesFechaCierrePasadaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.viajesFechaCierrePasadaCompleted(this, new viajesFechaCierrePasadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findByPromoter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("findByPromoter", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindByPromoter(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findByPromoter", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindByPromoter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findByPromoterAsync(long arg0, bool arg0Specified) {
        this.findByPromoterAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void findByPromoterAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.findByPromoterOperationCompleted == null)) {
            this.findByPromoterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByPromoterOperationCompleted);
        }
        this.InvokeAsync("findByPromoter", new object[] {
                    arg0,
                    arg0Specified}, this.findByPromoterOperationCompleted, userState);
    }
    
    private void OnfindByPromoterOperationCompleted(object arg) {
        if ((this.findByPromoterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByPromoterCompleted(this, new findByPromoterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findAllDisponible() {
        object[] results = this.Invoke("findAllDisponible", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAllDisponible(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAllDisponible", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindAllDisponible(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllDisponibleAsync() {
        this.findAllDisponibleAsync(null);
    }
    
    /// <remarks/>
    public void findAllDisponibleAsync(object userState) {
        if ((this.findAllDisponibleOperationCompleted == null)) {
            this.findAllDisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllDisponibleOperationCompleted);
        }
        this.InvokeAsync("findAllDisponible", new object[0], this.findAllDisponibleOperationCompleted, userState);
    }
    
    private void OnfindAllDisponibleOperationCompleted(object arg) {
        if ((this.findAllDisponibleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllDisponibleCompleted(this, new findAllDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findLastMonthTrip() {
        object[] results = this.Invoke("findLastMonthTrip", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindLastMonthTrip(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findLastMonthTrip", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindLastMonthTrip(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findLastMonthTripAsync() {
        this.findLastMonthTripAsync(null);
    }
    
    /// <remarks/>
    public void findLastMonthTripAsync(object userState) {
        if ((this.findLastMonthTripOperationCompleted == null)) {
            this.findLastMonthTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindLastMonthTripOperationCompleted);
        }
        this.InvokeAsync("findLastMonthTrip", new object[0], this.findLastMonthTripOperationCompleted, userState);
    }
    
    private void OnfindLastMonthTripOperationCompleted(object arg) {
        if ((this.findLastMonthTripCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findLastMonthTripCompleted(this, new findLastMonthTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findAllDisponibleUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("findAllDisponibleUser", new object[] {
                    arg0});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAllDisponibleUser(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAllDisponibleUser", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindAllDisponibleUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllDisponibleUserAsync(string arg0) {
        this.findAllDisponibleUserAsync(arg0, null);
    }
    
    /// <remarks/>
    public void findAllDisponibleUserAsync(string arg0, object userState) {
        if ((this.findAllDisponibleUserOperationCompleted == null)) {
            this.findAllDisponibleUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllDisponibleUserOperationCompleted);
        }
        this.InvokeAsync("findAllDisponibleUser", new object[] {
                    arg0}, this.findAllDisponibleUserOperationCompleted, userState);
    }
    
    private void OnfindAllDisponibleUserOperationCompleted(object arg) {
        if ((this.findAllDisponibleUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllDisponibleUserCompleted(this, new findAllDisponibleUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trip.impl.business.sdi.com/", ResponseNamespace="http://trip.impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] findAllTrip() {
        object[] results = this.Invoke("findAllTrip", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindAllTrip(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findAllTrip", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndfindAllTrip(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void findAllTripAsync() {
        this.findAllTripAsync(null);
    }
    
    /// <remarks/>
    public void findAllTripAsync(object userState) {
        if ((this.findAllTripOperationCompleted == null)) {
            this.findAllTripOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllTripOperationCompleted);
        }
        this.InvokeAsync("findAllTrip", new object[0], this.findAllTripOperationCompleted, userState);
    }
    
    private void OnfindAllTripOperationCompleted(object arg) {
        if ((this.findAllTripCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findAllTripCompleted(this, new findAllTripCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public partial class registrarViajeDto {
    
    private string adressFromField;
    
    private string adressToField;
    
    private string availableSeatsField;
    
    private string cityFromField;
    
    private string cityToField;
    
    private string commentTripField;
    
    private string countryFromField;
    
    private string countryToField;
    
    private System.DateTime dateFromField;
    
    private bool dateFromFieldSpecified;
    
    private System.DateTime dateLimitField;
    
    private bool dateLimitFieldSpecified;
    
    private System.DateTime dateToField;
    
    private bool dateToFieldSpecified;
    
    private long idUsuarioField;
    
    private bool idUsuarioFieldSpecified;
    
    private long idViajeField;
    
    private bool idViajeFieldSpecified;
    
    private string latZipCodeFromField;
    
    private string latZipCodeToField;
    
    private string longZipCodeFromField;
    
    private string longZipCodeToField;
    
    private string maxSeatsField;
    
    private string postalCodeFromField;
    
    private string postalCodeToField;
    
    private string priceTripField;
    
    private long promoterField;
    
    private bool promoterFieldSpecified;
    
    private string provinceFromField;
    
    private string provinceToField;
    
    private string resultField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adressFrom {
        get {
            return this.adressFromField;
        }
        set {
            this.adressFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adressTo {
        get {
            return this.adressToField;
        }
        set {
            this.adressToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string availableSeats {
        get {
            return this.availableSeatsField;
        }
        set {
            this.availableSeatsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cityFrom {
        get {
            return this.cityFromField;
        }
        set {
            this.cityFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cityTo {
        get {
            return this.cityToField;
        }
        set {
            this.cityToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string commentTrip {
        get {
            return this.commentTripField;
        }
        set {
            this.commentTripField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countryFrom {
        get {
            return this.countryFromField;
        }
        set {
            this.countryFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countryTo {
        get {
            return this.countryToField;
        }
        set {
            this.countryToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateFromSpecified {
        get {
            return this.dateFromFieldSpecified;
        }
        set {
            this.dateFromFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateLimit {
        get {
            return this.dateLimitField;
        }
        set {
            this.dateLimitField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateLimitSpecified {
        get {
            return this.dateLimitFieldSpecified;
        }
        set {
            this.dateLimitFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateTo {
        get {
            return this.dateToField;
        }
        set {
            this.dateToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateToSpecified {
        get {
            return this.dateToFieldSpecified;
        }
        set {
            this.dateToFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idUsuario {
        get {
            return this.idUsuarioField;
        }
        set {
            this.idUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idUsuarioSpecified {
        get {
            return this.idUsuarioFieldSpecified;
        }
        set {
            this.idUsuarioFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idViaje {
        get {
            return this.idViajeField;
        }
        set {
            this.idViajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idViajeSpecified {
        get {
            return this.idViajeFieldSpecified;
        }
        set {
            this.idViajeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string latZipCodeFrom {
        get {
            return this.latZipCodeFromField;
        }
        set {
            this.latZipCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string latZipCodeTo {
        get {
            return this.latZipCodeToField;
        }
        set {
            this.latZipCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longZipCodeFrom {
        get {
            return this.longZipCodeFromField;
        }
        set {
            this.longZipCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longZipCodeTo {
        get {
            return this.longZipCodeToField;
        }
        set {
            this.longZipCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maxSeats {
        get {
            return this.maxSeatsField;
        }
        set {
            this.maxSeatsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCodeFrom {
        get {
            return this.postalCodeFromField;
        }
        set {
            this.postalCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCodeTo {
        get {
            return this.postalCodeToField;
        }
        set {
            this.postalCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priceTrip {
        get {
            return this.priceTripField;
        }
        set {
            this.priceTripField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long promoter {
        get {
            return this.promoterField;
        }
        set {
            this.promoterField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promoterSpecified {
        get {
            return this.promoterFieldSpecified;
        }
        set {
            this.promoterFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string provinceFrom {
        get {
            return this.provinceFromField;
        }
        set {
            this.provinceFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string provinceTo {
        get {
            return this.provinceToField;
        }
        set {
            this.provinceToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public partial class modificarViajeDto {
    
    private string adressFromField;
    
    private string adressToField;
    
    private string availableSeatsField;
    
    private string cityFromField;
    
    private string cityToField;
    
    private string commentTripField;
    
    private string countryFromField;
    
    private string countryToField;
    
    private System.DateTime dateFromField;
    
    private bool dateFromFieldSpecified;
    
    private System.DateTime dateLimitField;
    
    private bool dateLimitFieldSpecified;
    
    private System.DateTime dateToField;
    
    private bool dateToFieldSpecified;
    
    private long idViajeField;
    
    private bool idViajeFieldSpecified;
    
    private string latZipCodeFromField;
    
    private string latZipCodeToField;
    
    private string longZipCodeFromField;
    
    private string longZipCodeToField;
    
    private string maxSeatsField;
    
    private string postalCodeFromField;
    
    private string postalCodeToField;
    
    private string priceTripField;
    
    private long promoterField;
    
    private bool promoterFieldSpecified;
    
    private string provinceFromField;
    
    private string provinceToField;
    
    private string resultField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adressFrom {
        get {
            return this.adressFromField;
        }
        set {
            this.adressFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adressTo {
        get {
            return this.adressToField;
        }
        set {
            this.adressToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string availableSeats {
        get {
            return this.availableSeatsField;
        }
        set {
            this.availableSeatsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cityFrom {
        get {
            return this.cityFromField;
        }
        set {
            this.cityFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cityTo {
        get {
            return this.cityToField;
        }
        set {
            this.cityToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string commentTrip {
        get {
            return this.commentTripField;
        }
        set {
            this.commentTripField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countryFrom {
        get {
            return this.countryFromField;
        }
        set {
            this.countryFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countryTo {
        get {
            return this.countryToField;
        }
        set {
            this.countryToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateFromSpecified {
        get {
            return this.dateFromFieldSpecified;
        }
        set {
            this.dateFromFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateLimit {
        get {
            return this.dateLimitField;
        }
        set {
            this.dateLimitField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateLimitSpecified {
        get {
            return this.dateLimitFieldSpecified;
        }
        set {
            this.dateLimitFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateTo {
        get {
            return this.dateToField;
        }
        set {
            this.dateToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateToSpecified {
        get {
            return this.dateToFieldSpecified;
        }
        set {
            this.dateToFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idViaje {
        get {
            return this.idViajeField;
        }
        set {
            this.idViajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idViajeSpecified {
        get {
            return this.idViajeFieldSpecified;
        }
        set {
            this.idViajeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string latZipCodeFrom {
        get {
            return this.latZipCodeFromField;
        }
        set {
            this.latZipCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string latZipCodeTo {
        get {
            return this.latZipCodeToField;
        }
        set {
            this.latZipCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longZipCodeFrom {
        get {
            return this.longZipCodeFromField;
        }
        set {
            this.longZipCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longZipCodeTo {
        get {
            return this.longZipCodeToField;
        }
        set {
            this.longZipCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maxSeats {
        get {
            return this.maxSeatsField;
        }
        set {
            this.maxSeatsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCodeFrom {
        get {
            return this.postalCodeFromField;
        }
        set {
            this.postalCodeFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCodeTo {
        get {
            return this.postalCodeToField;
        }
        set {
            this.postalCodeToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priceTrip {
        get {
            return this.priceTripField;
        }
        set {
            this.priceTripField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long promoter {
        get {
            return this.promoterField;
        }
        set {
            this.promoterField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promoterSpecified {
        get {
            return this.promoterFieldSpecified;
        }
        set {
            this.promoterFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string provinceFrom {
        get {
            return this.provinceFromField;
        }
        set {
            this.provinceFromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string provinceTo {
        get {
            return this.provinceToField;
        }
        set {
            this.provinceToField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public partial class waypoint {
    
    private double latField;
    
    private bool latFieldSpecified;
    
    private double lonField;
    
    private bool lonFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latSpecified {
        get {
            return this.latFieldSpecified;
        }
        set {
            this.latFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lonSpecified {
        get {
            return this.lonFieldSpecified;
        }
        set {
            this.lonFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public partial class addressPoint {
    
    private string addressField;
    
    private string cityField;
    
    private string countryField;
    
    private string stateField;
    
    private waypoint waypointField;
    
    private string zipCodeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <comentarios/>
    public waypoint waypoint {
        get {
            return this.waypointField;
        }
        set {
            this.waypointField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public partial class trip {
    
    private System.DateTime arrivalDateField;
    
    private bool arrivalDateFieldSpecified;
    
    private int availablePaxField;
    
    private bool availablePaxFieldSpecified;
    
    private string cityDestinationField;
    
    private System.DateTime closingDateField;
    
    private bool closingDateFieldSpecified;
    
    private string commentsField;
    
    private addressPoint departureField;
    
    private System.DateTime departureDateField;
    
    private bool departureDateFieldSpecified;
    
    private addressPoint destinationField;
    
    private double estimatedCostField;
    
    private bool estimatedCostFieldSpecified;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private int maxPaxField;
    
    private bool maxPaxFieldSpecified;
    
    private long promoterIdField;
    
    private bool promoterIdFieldSpecified;
    
    private tripStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime arrivalDate {
        get {
            return this.arrivalDateField;
        }
        set {
            this.arrivalDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool arrivalDateSpecified {
        get {
            return this.arrivalDateFieldSpecified;
        }
        set {
            this.arrivalDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int availablePax {
        get {
            return this.availablePaxField;
        }
        set {
            this.availablePaxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool availablePaxSpecified {
        get {
            return this.availablePaxFieldSpecified;
        }
        set {
            this.availablePaxFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cityDestination {
        get {
            return this.cityDestinationField;
        }
        set {
            this.cityDestinationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime closingDate {
        get {
            return this.closingDateField;
        }
        set {
            this.closingDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closingDateSpecified {
        get {
            return this.closingDateFieldSpecified;
        }
        set {
            this.closingDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint departure {
        get {
            return this.departureField;
        }
        set {
            this.departureField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime departureDate {
        get {
            return this.departureDateField;
        }
        set {
            this.departureDateField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool departureDateSpecified {
        get {
            return this.departureDateFieldSpecified;
        }
        set {
            this.departureDateFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double estimatedCost {
        get {
            return this.estimatedCostField;
        }
        set {
            this.estimatedCostField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimatedCostSpecified {
        get {
            return this.estimatedCostFieldSpecified;
        }
        set {
            this.estimatedCostFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxPax {
        get {
            return this.maxPaxField;
        }
        set {
            this.maxPaxField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxPaxSpecified {
        get {
            return this.maxPaxFieldSpecified;
        }
        set {
            this.maxPaxFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long promoterId {
        get {
            return this.promoterIdField;
        }
        set {
            this.promoterIdField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promoterIdSpecified {
        get {
            return this.promoterIdFieldSpecified;
        }
        set {
            this.promoterIdFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public tripStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trip.impl.business.sdi.com/")]
public enum tripStatus {
    
    /// <comentarios/>
    OPEN,
    
    /// <comentarios/>
    CLOSED,
    
    /// <comentarios/>
    CANCELLED,
    
    /// <comentarios/>
    DONE,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://trip.impl.business.sdi.com/")]
public partial class cancelarViajesEntry {
    
    private long keyField;
    
    private bool keyFieldSpecified;
    
    private trip valueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified {
        get {
            return this.keyFieldSpecified;
        }
        set {
            this.keyFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void registrarCompletedEventHandler(object sender, registrarCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByIdTripCompletedEventHandler(object sender, findByIdTripCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByIdTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByIdTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findViajesHaParticipadoCompletedEventHandler(object sender, findViajesHaParticipadoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findViajesHaParticipadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findViajesHaParticipadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void cancelarViajesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void liberarPlazaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void actualizarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void modificarCompletedEventHandler(object sender, modificarCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class modificarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal modificarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByPromoterAndAvailablePaxCompletedEventHandler(object sender, findByPromoterAndAvailablePaxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByPromoterAndAvailablePaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByPromoterAndAvailablePaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByPromoterAndDoneCompletedEventHandler(object sender, findByPromoterAndDoneCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByPromoterAndDoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByPromoterAndDoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByAceptadoCompletedEventHandler(object sender, findByAceptadoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByAceptadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByAceptadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ocuparPlazaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void cerrarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void viajesFechaCierrePasadaCompletedEventHandler(object sender, viajesFechaCierrePasadaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class viajesFechaCierrePasadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal viajesFechaCierrePasadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findByPromoterCompletedEventHandler(object sender, findByPromoterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByPromoterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByPromoterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllDisponibleCompletedEventHandler(object sender, findAllDisponibleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllDisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllDisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findLastMonthTripCompletedEventHandler(object sender, findLastMonthTripCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findLastMonthTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findLastMonthTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllDisponibleUserCompletedEventHandler(object sender, findAllDisponibleUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllDisponibleUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllDisponibleUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void findAllTripCompletedEventHandler(object sender, findAllTripCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findAllTripCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findAllTripCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}
